name: Test Examples

on:
  push:
    paths:
      - 'gym_nim/**'
      - 'examples/**'
      - 'setup.py'
  pull_request:
    paths:
      - 'gym_nim/**'
      - 'examples/**'
      - 'setup.py'

jobs:
  test-examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.12']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install setuptools first for compatibility
        pip install "setuptools<70"
        # Install gym and numpy directly
        pip install "gym==0.9.1" numpy
        # Try to install the package
        pip install -e . || echo "Installation might have warnings"
    
    - name: Test random_nim example
      run: |
        # Run for just a few episodes to test it works
        python -c "
import gym
import gym_nim
import random

env = gym.make('nim-v0')
for episode in range(3):
    state = env.reset()
    done = False
    steps = 0
    while not done and steps < 20:
        moves = env.move_generator()
        if moves:
            action = random.choice(moves)
            state, reward, done, _ = env.step(action)
        else:
            break
        steps += 1
    print(f'Episode {episode} completed in {steps} steps')
"
    
    - name: Check qtable example syntax
      run: |
        # Just check if the file can be parsed
        python -m py_compile examples/qtable.py