name: Test Examples

on:
  push:
    paths:
      - 'gym_nim/**'
      - 'examples/**'
      - 'setup.py'
  pull_request:
    paths:
      - 'gym_nim/**'
      - 'examples/**'
      - 'setup.py'

jobs:
  test-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.8']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test random_nim example
      run: |
        # Run for just a few episodes to test it works
        python -c "
import gym
import gym_nim
import random

env = gym.make('nim-v0')
for episode in range(3):
    state = env.reset()
    done = False
    steps = 0
    while not done and steps < 20:
        moves = env.move_generator()
        if moves:
            action = random.choice(moves)
            state, reward, done, _ = env.step(action)
        else:
            break
        steps += 1
    print(f'Episode {episode} completed in {steps} steps')
"
    
    - name: Check qtable example syntax
      run: |
        # Just check if the file can be parsed
        python -m py_compile examples/qtable.py